### ISSUE TITLE
Solution for module acquistion in latest update

### ISSUE THREAD

**Issue by Damillora** [biuuu/ShinyColors#56]
With the latest game update, the app is loaded directly through HTML, so hijacking eval no longer works.

In the English patch, I devised a solution by executing the patch script very early, and intercepting script loading with the "beforescriptexecute" event. This event is only natively available on Firefox, so I imported a polyfill to get the event on other browsers too.

The commit detailing the implementation in the English patch is https://github.com/snowyivu/ShinyColors/commit/808664c36bd9b60cda352321750aecfefbf31f02

I opened an issue first instead of directly sending a pull request because difference in implementation details made me unsure if this works in the Chinese patch too.

**Comment by biuuu** [comment]
thanks for your reminder. I used a few other methods to solve the problem.
But considering that enza's recent updates may be for the Patch.
I decided to use a private repo to update the code and compress the published script.
https://github.com/biuuu/ShinyColors/tree/gh-pages

**Comment by Damillora** [comment]
Thanks for the heads up too! Guess the English patch needs to move to a private repo too.
