### ISSUE TITLE
chrome浏览器下运行脚本时出现的一些问题

### ISSUE THREAD

**Issue by naruuu-xx** [biuuu/ShinyColors#61]
在油猴安装正确，脚本安装正确的情况下
1.打开游戏网页 游戏内图标显示不完全，关闭脚本后恢复正常。
2.调整窗口尺寸这个脚本选项无法使用
![image](https://user-images.githubusercontent.com/75790544/106350172-c920e400-630e-11eb-8549-98ac24137ad0.png)

**Comment by biuuu** [comment]
图片加载失败，可能你的网络访问 www.shiny.fun 不稳定。
调整窗口尺寸只有在将游戏安装为浏览器应用，并且窗口模式打开的情况下有用。

**Comment by naruuu-xx** [comment]
> 图片加载失败，可能你的网络访问 [www.shiny.fun](http://www.shiny.fun) 不稳定。
> 调整窗口尺寸只有在将游戏安装为浏览器应用，并且窗口模式打开的情况下有用。

谢谢 了解了！ 但是同样的节点用火狐浏览器运行游戏网页就没问题  现在转为火狐浏览器玩了 chrome在脚本运行下无法加载完全图标的问题 依旧无解

**Comment by biuuu** [comment]
可以看看chrome版本是多少，用的 Violentmonkey 还是 Tampermonkey，对应的版本是多少。
