### ISSUE TITLE
IOS15 支持安装油猴脚本.

### ISSUE THREAD

**Issue by Andor233** [biuuu/ShinyColors#68]
我的其他脚本都能工作正常, 但是这个翻译完全没有生效?

**Comment by biuuu** [comment]
因为游戏代码的限制，这个脚本必须在游戏代码运行之前执行才行。
iOS是通过第三方扩展支持的油猴脚本，可能没实现尽早加载脚本的功能。

**Comment by biuuu** [comment]
用 stay 安装新的汉化脚本，可以在 safari 上汉化了。

**Comment by Andor233** [comment]
> 用 stay 安装新的汉化脚本，可以在 safari 上汉化了。

stay是什么？

**Comment by biuuu** [comment]
App

**Comment by Andor233** [comment]
> App

Appstore 没搜到来着。。

**Comment by biuuu** [comment]
![image](https://user-images.githubusercontent.com/10892119/192216754-1c22057f-02a2-464c-8f9c-491425ddd825.png)

**Comment by biuuu** [comment]
https://www.bilibili.com/video/BV1WT411T7dU
