### ISSUE TITLE
Translation of skill names containing forward slashes does not work correctly

### ISSUE THREAD

**Issue by Gnbrkm41** [biuuu/ShinyColors#71]
https://github.com/biuuu/ShinyColors/blob/dbe377bffd632c7b5ec362f15a8c75ad774362ac/src/modules/api-comm.js#L58-L71

Here, we `split` the string to translate by `/` (Line 60) before looking for the substitution string on skill.csv. I imagine this is for translation of slash-separated skill effects, however this actually causes skill names containing slashes to be not translated correctly. For example, take a look at Nichika's 2nd P-SSR:
![Screenshot_20220724_202536](https://user-images.githubusercontent.com/42944058/180644849-16483042-9338-4bcf-b26c-5992ca30eefb.png)

What happens is that since the skill name contains a forward slash (`[7/31]超順調ですよ`), this gets split into two parts (`[7` and `31]超順調ですよ`) before looking for substitutions; therefore, if you were to put translation data such as `[7/31]超順調ですよ,[7/31]완전 순조로워요,text` in the skill.csv file, the script will fail to find the substitute as it's not looking for the complete string, rather in parts.

One workaround is to enter translations for the individual parts manually, like:
```text
[7,[7,text
31]超順調ですよ,31]완전 순조로워요,text
```
However this would be super confusing as to why they're split like that, so I'd like the fix be made in the source instead if possible.

Suggested code would be something like:
```js
const transItem = (item, key, data = commData) => {
  if (item?.[key]) {
    let arr = key == "name" ? [ item[key] ] : item[key].split('/')
    arr.forEach((txt, index) => {
      let plusList = nameWithPlus(arr)
      replaceItem(arr, index, data)
      nameWithPlus(arr, plusList)
    })
    let text = arr.join('/')
    if (text !== item[key]) {
      item[key] = tagText(text, true)
    }
  }
}
```

I'm not sure if this is really viable elsewhere as I do not know where else the transItem function is used in. As far as I know there's no `name`s that needs to be translated in parts so I imagine this would be fine? 😅

**Comment by Gnbrkm41** [comment]
After some conversation, it turns out that skill names that use slashes do actually exist: 
https://github.com/biuuu/ShinyColors/blob/dbe377bffd632c7b5ec362f15a8c75ad774362ac/src/modules/skill/comm-skill.js#L38

![Screenshot_20220724_234547](https://user-images.githubusercontent.com/42944058/180652453-56bf6116-f12a-4200-b191-e7ad0eafb968.png)

Here, the `Dance60％UP/注目度30％UP` part is accessible as `passiveSkills[i].name`. With the aforementioned change, this will no longer get split into two pieces. So this actually would end up breaking those passive skill name translations if the translation type is marked as `text`. Which is bad! (should 6cdfb22 should be reverted?)

One other solution I can think of would be to essentially make a copy of the function that doesn't split by slashes, then use that when translating non-slash-separated names...

**Comment by Gnbrkm41** [comment]
cc @biuuu should 6cdfb22 should be reverted?

**Comment by biuuu** [comment]
I changed the code to try to replace the complete text first, and if the text has been replaced after that, no longer `split('/')`.
b695f94f8820011d49332dea2d964a8f3f1fe75c

**Comment by Gnbrkm41** [comment]
Great, thanks!
