### ISSUE TITLE
Translations with exact text match only are prioritised over translations with id match

### ISSUE THREAD

**Issue by Gnbrkm41** [biuuu/ShinyColors#75]
Consider 線たちの12月 Scenario event's last commu (game_event_communications/400105508.json):

![image](https://user-images.githubusercontent.com/42944058/207851952-66c71520-fc38-440e-9684-ab4f843c996f.png)
There exists a line without an ID, which the original text is  "──────" and the translation is also  "──────".

![image](https://user-images.githubusercontent.com/42944058/207851977-56a80116-1c00-47c4-ac0f-9c87564c535d.png)
Also, there exists two lines with IDs 4001055081061 and 4001055081062 respectively, that also has original text value of "──────" but has a proper translation (added for convenience reasons since it does have a voiceline)

When the translation CSV is read by the script, translations are put into a `Map` where the key is the original text if ID is nonexistent, or the ID is the key if the key does exist:

![image](https://user-images.githubusercontent.com/42944058/207853210-4025b55f-574d-4863-a204-4debf69c2d31.png)
Map entry of the first line without an ID (index 72)

![image](https://user-images.githubusercontent.com/42944058/207853222-901ebfbd-97e4-4dd7-be83-4efd6f2df5cb.png)
Map entries of the lines with an ID (index 139 and 140)

The problematic part is here: https://github.com/biuuu/ShinyColors/blob/f8da1d36454b4c764230974ed9c40bf8b86380fe/src/modules/story.js#L75-L88

Since L81 which checks for the key with the exact match comes first, translations for 4001055081061 and 4001055081062 are ignored as there exists an exact match where only the original text ("──────") matches. Therefore the translation for the ID-less line is used for both of the lines, which is the same as before. This is how it looks in-game:
![image](https://user-images.githubusercontent.com/42944058/207853885-2dbb7278-12dc-4f96-96e6-52013ce72b39.png)

~~It feels like it would be fine to just swap the order of the checks, so ID check at L83-84 comes first before the text only check at L81-82, but I could be wrong.~~

**Comment by Gnbrkm41** [comment]
I've just heard that there is a reason text is checked first instead of the ID, something on the line of ID being non-unique in certain commus added early in the game?? Not sure how we should handle this then...

**Comment by biuuu** [comment]
I can't remember exactly what happened to duplicate IDs, but I see that the solution has been written in the code.
L76: `const getId = uniqueStoryId()`
Maybe it will not be a problem to directly change to match the ID first.

**Comment by Gnbrkm41** [comment]
Closing as resolved for now.
